Site\CoreBundle\Entity\NewsCategory:
    type: entity
    table: null
    repositoryClass: Site\CoreBundle\Entity\NewsCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idNews:
            type: string
            length: 255
            column: id_news
        idCategory:
            type: string
            length: 255
            column: id_category
    lifecycleCallbacks: {  }
