Site\CoreBundle\Entity\Tags:
    type: entity
    table: null
    repositoryClass: Site\CoreBundle\Entity\TagsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToMany:
        name:
            targetEntity: News
            mappedBy: tags
    lifecycleCallbacks: {  }
