Site\CoreBundle\Entity\Tags:
    type: entity
    table: null
    repositoryClass: Site\CoreBundle\Entity\TagsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    #manyToMany:
    #   name:
    #       targetEntity: News
    #       mappedBy: tags
    lifecycleCallbacks: {  }
